"use client";

import { useState } from "react";
import { ArrowRight, BookOpen, Check, CheckCircle2, ChevronRight, Clock3, Command, Copy, ExternalLink, HelpCircle, Layers3, Menu, Play, Search, Sparkles, Terminal } from "lucide-react";

const themes = [
  { id: "command", n: "01", name: "Obsidian Command", note: "Premium developer portal" },
  { id: "swiss", n: "02", name: "Swiss Precision", note: "Clean global documentation" },
  { id: "aurora", n: "03", name: "Aurora Glass", note: "Modern AI product guide" },
  { id: "editorial", n: "04", name: "Editorial Paper", note: "Elegant long-form manual" },
  { id: "blueprint", n: "05", name: "Blueprint Studio", note: "Technical setup workflow" },
  { id: "bento", n: "06", name: "Bento Atlas", note: "Visual modular onboarding" },
  { id: "nordic", n: "07", name: "Nordic Calm", note: "Accessible guided setup" },
  { id: "brutal", n: "08", name: "Neo Brutalist", note: "Bold memorable handbook" },
  { id: "canvas", n: "09", name: "Gradient Canvas", note: "Friendly SaaS onboarding" },
  { id: "terminal", n: "10", name: "Terminal Pro", note: "CLI-first installation" },
] as const;

type ThemeId = (typeof themes)[number]["id"];
const steps = [
  { title: "Create your workspace", text: "Choose a name, region, and workspace visibility.", time: "2 min" },
  { title: "Install the toolkit", text: "Run one command or use the guided desktop installer.", time: "3 min" },
  { title: "Connect your project", text: "Link a repository and confirm the detected settings.", time: "2 min" },
  { title: "Run your first workflow", text: "Launch a sample task and review the generated output.", time: "4 min" },
];

const MiniLogo = () => <span className="mini-logo"><Sparkles size={15} strokeWidth={2.4}/></span>;
const Progress = ({ dark = false }: { dark?: boolean }) => <div className={`progress-line ${dark ? "is-dark" : ""}`}><span style={{width:"25%"}}/></div>;
const CodeBlock = ({ light = false, prompt = true }: { light?: boolean; prompt?: boolean }) => <div className={`code-block ${light?"is-light":""}`}><div className="code-top"><span/><span/><span/><small>Terminal</small><button aria-label="Copy command"><Copy size={14}/></button></div><code>{prompt&&<b>$ </b>}npm install -g nova-cli</code></div>;
const Checklist = ({ compact=false }: { compact?:boolean }) => <div className={`checklist ${compact?"compact":""}`}>{["Node.js 20 or later","Git 2.40 or later","An active workspace"].map(item=><div key={item}><Check size={14}/><span>{item}</span></div>)}</div>;

function CommandLayout(){return <div className="guide command-layout"><aside><div className="brand"><MiniLogo/><b>NOVA</b><span>DOCS</span></div><nav><small>GET STARTED</small>{["Introduction","Quick start","Installation","Configuration"].map((x,i)=><a className={i===1?"active":""} key={x}>{x}{i===1&&<ChevronRight size={14}/>}</a>)}<small>WORKFLOWS</small>{["Projects","Automations","Deployment"].map(x=><a key={x}>{x}</a>)}</nav><div className="aside-help"><HelpCircle size={17}/><div><b>Need help?</b><span>Visit support center</span></div></div></aside><section className="command-main"><header><div className="search"><Search size={16}/><span>Search documentation...</span><kbd>⌘ K</kbd></div><button><ExternalLink size={15}/> Dashboard</button></header><main><div className="eyebrow">GETTING STARTED <ChevronRight size={13}/> QUICK START</div><h1>Build your first<br/><em>workflow.</em></h1><p className="lead">Go from zero to a running automation in under ten minutes. We’ll guide you through every step.</p><div className="meta"><span><Clock3 size={15}/> 10 min</span><span>Beginner</span></div><div className="step-card"><div className="step-num">01</div><div className="step-copy"><span className="overline">INSTALL THE CLI</span><h2>Set up your toolkit</h2><p>Open your terminal and install the Nova command-line interface globally.</p><CodeBlock/></div><CheckCircle2 className="done" size={22}/></div><div className="next-row"><span>Up next</span><b>Create your workspace</b><ArrowRight size={18}/></div></main><div className="toc"><small>ON THIS PAGE</small><a className="active">Install the CLI</a><a>Create a workspace</a><a>Connect a project</a><a>Run a workflow</a><div><b>25%</b><Progress dark/></div></div></section></div>}

function SwissLayout(){return <div className="guide swiss-layout"><header><div className="swiss-brand"><span>N</span><b>NOVA / GUIDE</b></div><nav><a>Documentation</a><a>API</a><a>Examples</a></nav><button><Search size={17}/> Search <kbd>⌘K</kbd></button></header><main><div className="swiss-index"><span>01—04</span><strong>QUICK<br/>START</strong><p>Everything you need to launch your first project.</p><div className="vertical-word">DOCUMENTATION</div></div><article><div className="swiss-kicker"><span>GETTING STARTED</span><span>10 MIN READ</span></div><h1>Your first workflow,<br/>from start to <i>finish.</i></h1><p className="intro">A concise guide to installing Nova, creating a workspace, and running a production-ready workflow.</p><div className="swiss-grid">{steps.map((s,i)=><section key={s.title}><span className="big-num">0{i+1}</span><div><h2>{s.title}</h2><p>{s.text}</p>{i===1&&<code>npm i -g nova-cli</code>}</div><ArrowRight size={19}/></section>)}</div></article></main></div>}

function AuroraLayout(){return <div className="guide aurora-layout"><div className="aurora-orb orb-one"/><div className="aurora-orb orb-two"/><header><div className="brand"><MiniLogo/><b>nova</b></div><nav><a>Guides</a><a>Reference</a><a>Community</a></nav><div><button className="ghost"><Search size={17}/></button><button className="primary">Open console <ArrowRight size={15}/></button></div></header><main><div className="aurora-hero"><span className="pill"><Sparkles size={13}/> QUICK START</span><h1>Let’s make something<br/><em>brilliant.</em></h1><p>Four simple steps. One powerful workflow. Your first Nova project starts here.</p><div className="hero-actions"><button className="primary"><Play size={15} fill="currentColor"/> Start setup</button><span><Clock3 size={15}/> About 10 minutes</span></div></div><div className="glass-board"><div className="glass-top"><div><small>YOUR PROGRESS</small><b>1 of 4 complete</b></div><div className="rings"><span>25%</span></div></div><div className="glass-steps">{steps.map((s,i)=><article className={i===0?"active":""} key={s.title}><span>{i===0?<Check size={16}/>:i+1}</span><div><small>STEP 0{i+1}</small><h3>{s.title}</h3><p>{s.text}</p></div><ChevronRight size={17}/></article>)}</div></div></main></div>}

function EditorialLayout(){return <div className="guide editorial-layout"><header><div className="issue">NOVA<br/><span>FIELD GUIDE</span></div><nav><a>Guides</a><a>Stories</a><a>Reference</a></nav><div className="edition">VOL. 01 · 2026 <Menu size={21}/></div></header><main><div className="editorial-title"><div><span>THE ESSENTIAL GUIDE / 01</span><h1>Start here.<br/><i>Go anywhere.</i></h1></div><p>A thoughtfully composed introduction to Nova—designed to take you from an empty workspace to your first successful workflow.</p></div><div className="editorial-rule"><span>10 MINUTE READ</span><span>WORDS BY NOVA TEAM</span><span>UPDATED AUGUST 2026</span></div><div className="editorial-body"><aside><span>IN THIS GUIDE</span>{steps.map((s,i)=><a className={i===0?"active":""} key={s.title}>0{i+1} / {s.title}</a>)}</aside><article><span className="dropcap">B</span><p className="first">efore you begin, make sure your local environment is ready. Nova is designed to feel lightweight, predictable, and remarkably fast.</p><h2>01. Prepare your toolkit</h2><p>Installation takes a single command. Open your terminal, paste the line below, and Nova will take care of the rest.</p><CodeBlock light/><blockquote>“A good setup disappears. It gives you confidence, then gets out of the way.”</blockquote></article><aside className="note"><span>REQUIREMENTS</span><Checklist/></aside></div></main></div>}

function BlueprintLayout(){return <div className="guide blueprint-layout"><header><div className="blue-brand"><span><Command size={19}/></span><b>NOVA SYSTEMS</b><small>SETUP BLUEPRINT / V4.2</small></div><div className="status"><i/> SYSTEMS OPERATIONAL</div></header><main><aside><span>PROJECT INDEX</span>{steps.map((s,i)=><a className={i===0?"active":""} key={s.title}><b>0{i+1}</b>{s.title}</a>)}<div className="spec"><span>SPECIFICATION</span><p>Difficulty</p><b>BEGINNER</b><p>Est. duration</p><b>10 MIN</b></div></aside><article><div className="coord">N 37.7749° / W 122.4194°</div><span className="outline-label">INSTALLATION SEQUENCE</span><h1>INITIALIZE<br/>YOUR <i>TOOLKIT</i></h1><p className="blue-lead">Technical procedure for configuring the Nova command environment on your local workstation.</p><div className="schematic"><div className="node complete"><span>01</span><b>RUNTIME</b><small>VERIFIED</small></div><ArrowRight/><div className="node active"><span>02</span><b>INSTALL</b><small>IN PROGRESS</small></div><ArrowRight/><div className="node"><span>03</span><b>AUTH</b><small>PENDING</small></div><ArrowRight/><div className="node"><span>04</span><b>LAUNCH</b><small>PENDING</small></div></div><div className="instruction"><span>COMMAND / 001</span><h2>Install the Nova CLI</h2><p>Execute the following command with administrator privileges.</p><CodeBlock/><div className="verification"><CheckCircle2/><div><b>EXPECTED OUTPUT</b><code>nova-cli@4.2.0 installed successfully</code></div></div></div></article></main></div>}

function BentoLayout(){return <div className="guide bento-layout"><header><div className="brand"><MiniLogo/><b>Nova</b><span>Learn</span></div><nav><a>Start</a><a>Explore</a><a>Reference</a></nav><button><Search size={17}/> Search guides</button></header><main><div className="bento-heading"><div><span>QUICK START COURSE</span><h1>Four moves to<br/><em>your first launch.</em></h1></div><p>Learn Nova by building something real. This guided path covers everything you need—and nothing you don’t.</p></div><div className="bento-grid"><article className="bento-feature"><span className="count">01</span><div className="feature-icon"><Terminal size={32}/></div><div><small>START HERE · 2 MIN</small><h2>Install your toolkit</h2><p>One command gives you everything you need.</p><CodeBlock/></div><button>Begin step <ArrowRight size={16}/></button></article><article className="bento-progress"><small>COURSE PROGRESS</small><div className="donut"><b>25</b><span>%</span></div><p>1 of 4 steps complete</p></article><article className="bento-require"><small>BEFORE YOU START</small><h3>Quick check</h3><Checklist compact/></article>{steps.slice(1).map((s,i)=><article className="bento-step" key={s.title}><span>0{i+2}</span><small>{s.time}</small><h3>{s.title}</h3><p>{s.text}</p><ArrowRight size={17}/></article>)}</div></main></div>}

function NordicLayout(){return <div className="guide nordic-layout"><header><div className="brand"><span>N</span><b>nova</b></div><nav><a>Learn</a><a>Docs</a><a>Support</a></nav><button><Search size={17}/></button></header><main><aside><div className="soft-icon"><BookOpen size={25}/></div><span>GETTING STARTED</span><h1>A calm start<br/>with Nova.</h1><p>Follow this short path and you’ll be ready to build in about ten minutes.</p><div className="soft-progress"><div><b>25%</b><span>complete</span></div><Progress/></div></aside><article><div className="nordic-head"><span>YOUR SETUP PATH</span><p>Four small steps. Take them at your own pace.</p></div>{steps.map((s,i)=><section className={i===0?"active":""} key={s.title}><div className="step-marker">{i===0?<Check size={16}/>:i+1}</div><div><small>STEP {i+1} · {s.time}</small><h2>{s.title}</h2><p>{s.text}</p>{i===0&&<><CodeBlock light/><button>Continue to workspace <ArrowRight size={16}/></button></>}</div></section>)}</article></main></div>}

function BrutalLayout(){return <div className="guide brutal-layout"><header><div className="brutal-logo">N!</div><b>NOVA<br/>USER GUIDE</b><nav><a>DOCS</a><a>API</a><a>HELP</a></nav><button>SEARCH /</button></header><main><div className="brutal-hero"><span>NO. 001 — QUICK START</span><h1>SHIP<br/>YOUR<br/><i>FIRST</i><br/>WORKFLOW.</h1><div className="sticker">10<br/><small>MIN</small></div><p>No fluff. No mystery. Four straight-forward steps from install to launch.</p><button>LET’S GO <ArrowRight/></button></div><div className="brutal-steps">{steps.map((s,i)=><article className={i===0?"active":""} key={s.title}><span>0{i+1}</span><div><small>{s.time.toUpperCase()}</small><h2>{s.title}</h2><p>{s.text}</p>{i===0&&<code>$ npm i -g nova-cli</code>}</div><ArrowRight size={26}/></article>)}</div></main></div>}

function CanvasLayout(){return <div className="guide canvas-layout"><header><div className="brand"><MiniLogo/><b>nova</b></div><nav><a>Product</a><a>Guides</a><a>Community</a></nav><div><button className="login">Sign in</button><button className="start">Open Nova</button></div></header><main><div className="canvas-copy"><span><Sparkles size={14}/> WELCOME TO NOVA</span><h1>Your best work<br/>starts <em>here.</em></h1><p>A friendly, step-by-step setup experience made to get you creating in minutes—not hours.</p><div className="avatars"><span>RK</span><span>AM</span><span>JL</span><small>Trusted by 12,000+ builders</small></div></div><div className="setup-card"><div className="card-head"><div><small>QUICK START</small><h2>Let’s get you set up</h2></div><span>~10 min</span></div><Progress/>{steps.map((s,i)=><section className={i===0?"active":""} key={s.title}><span>{i===0?<Check/>:i+1}</span><div><small>STEP {i+1}</small><b>{s.title}</b><p>{s.text}</p>{i===0&&<code>npm install -g nova-cli <Copy size={14}/></code>}</div>{i===0?<button>Continue <ArrowRight size={15}/></button>:<ChevronRight/>}</section>)}</div></main></div>}

function TerminalLayout(){return <div className="guide terminal-layout"><header><div className="term-brand"><span>&gt;_</span><b>NOVA.DOCS</b><small>v4.2</small></div><nav><a>~/start</a><a>~/commands</a><a>~/config</a></nav><button><Search size={16}/> ctrl+k</button></header><main><aside><div className="tree"><span>QUICKSTART/</span><a className="active">├── 01-install.md</a><a>├── 02-workspace.md</a><a>├── 03-connect.md</a><a>└── 04-launch.md</a><span>REFERENCE/</span><a>├── commands.md</a><a>└── config.md</a></div><div className="system"><i/> ALL SYSTEMS NORMAL</div></aside><article><div className="breadcrumbs">root / docs / quickstart / <b>install</b></div><div className="term-title"><span>01</span><div><small>QUICK_START_SEQUENCE</small><h1>Initialize<br/>your environment<span>_</span></h1></div></div><p className="term-lead">Complete the following operations to install and verify the Nova command-line toolkit.</p><div className="terminal-window"><div className="term-tabs"><span>●</span><span>●</span><span>●</span><b><Terminal size={14}/> bash — install</b><small>+</small></div><div className="term-body"><p><i># Install Nova globally</i></p><p><b>guest@nova</b>:~$ npm install -g nova-cli</p><p className="output">added 142 packages in 2.4s</p><p className="success">✓ nova-cli@4.2.0 installed successfully</p><p><b>guest@nova</b>:~$ nova --version<span className="cursor"/></p></div></div><div className="term-next"><div><small>NEXT OPERATION</small><b>02 — Create your workspace</b></div><button>CONTINUE <ArrowRight size={16}/></button></div></article></main></div>}

function renderTheme(id:ThemeId){const layouts:Record<ThemeId,React.ReactNode>={command:<CommandLayout/>,swiss:<SwissLayout/>,aurora:<AuroraLayout/>,editorial:<EditorialLayout/>,blueprint:<BlueprintLayout/>,bento:<BentoLayout/>,nordic:<NordicLayout/>,brutal:<BrutalLayout/>,canvas:<CanvasLayout/>,terminal:<TerminalLayout/>};return layouts[id]}

export default function App(){const[theme,setTheme]=useState<ThemeId>("command");const selected=themes.find(t=>t.id===theme)!;return <main className="gallery-shell"><div className="gallery-bar"><div className="gallery-title"><Layers3 size={19}/><div><b>Tool User Guide Gallery</b><span>10 premium UI/UX directions</span></div></div><div className="theme-picker"><label htmlFor="theme-select">SELECT A DESIGN</label><select id="theme-select" className="gallery-select native-gallery-select" value={theme} onChange={e=>setTheme(e.target.value as ThemeId)} aria-label="Select a user guide design">{themes.map(t=><option value={t.id} key={t.id}>{t.n} — {t.name}</option>)}</select><span className="theme-note">{selected.note}</span></div><div className="gallery-count"><b>{selected.n}</b><span>/ 10</span></div></div><div className="preview-frame" key={theme}>{renderTheme(theme)}</div></main>}
